basic installation

diff --git a/libexec/elmenv-install b/libexec/elmenv-install
--- a/libexec/elmenv-install
+++ b/libexec/elmenv-install
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Summary: Install a Elm version using ruby-build
+# Summary: Install a Elm version using elmenv
 #
 # Usage: elmenv install [-f] [-kvp] <version>
 #        elmenv install [-f] [-kvp] <definition-file>
@@ -10,7 +10,7 @@
 #   -f/--force         Install even if the version appears to be installed already
 #   -s/--skip-existing Skip if the version appears to be installed already
 #
-#   ruby-build options:
+#   elmenv options:
 #
 #   -k/--keep          Keep source tree in $ELMENV_BUILD_ROOT after installation
 #                      (defaults to $ELMENV_ROOT/sources)
@@ -18,8 +18,8 @@
 #   -p/--patch         Apply a patch from stdin before building
 #
 # For detailed information on installing Elm versions with
-# ruby-build, including a list of environment variables for adjusting
-# compilation, see: https://github.com/sstephenson/ruby-build#usage
+# elmenv, including a list of environment variables for adjusting
+# compilation, see: https://github.com/sonnym/elmenv#usage
 #
 set -e
 [ -n "$ELMENV_DEBUG" ] && set -x
@@ -28,32 +28,45 @@ if [ -z "$ELMENV_ROOT" ]; then
   ELMENV_ROOT="${HOME}/.elmenv"
 fi
 
-# Add `share/ruby-build/` directory from each elmenv plugin to the list of
-# paths where build definitions are looked up.
+# Add `share/versions/` directory to the list of paths where build definitions are looked up.
 shopt -s nullglob
-for plugin_path in "$ELMENV_ROOT"/plugins/*/share/ruby-build; do
+for plugin_path in "$ELMENV_ROOT"/share/versions; do
   ELM_BUILD_DEFINITIONS="${ELM_BUILD_DEFINITIONS}:${plugin_path}"
 done
 export ELM_BUILD_DEFINITIONS
 shopt -u nullglob
 
-# Provide elmenv completions
-if [ "$1" = "--complete" ]; then
-  exec ruby-build --definitions
-fi
+parse_options() {
+  OPTIONS=()
+  ARGUMENTS=()
+  local arg option index
 
-# Load shared library functions
-eval "$(ruby-build --lib)"
+  for arg in "$@"; do
+    if [ "${arg:0:1}" = "-" ]; then
+      if [ "${arg:1:1}" = "-" ]; then
+        OPTIONS[${#OPTIONS[*]}]="${arg:2}"
+      else
+        index=1
+        while option="${arg:$index:1}"; do
+          [ -n "$option" ] || break
+          OPTIONS[${#OPTIONS[*]}]="$option"
+          index=$(($index+1))
+        done
+      fi
+    else
+      ARGUMENTS[${#ARGUMENTS[*]}]="$arg"
+    fi
+  done
+}
 
 usage() {
-  # We can remove the sed fallback once elmenv 0.4.0 is widely available.
-  elmenv-help install 2>/dev/null || sed -ne '/^#/!q;s/.//;s/.//;1,4d;p' < "$0"
+  elmenv-help install 2>/dev/null
   [ -z "$1" ] || exit "$1"
 }
 
 definitions() {
   local query="$1"
-  ruby-build --definitions | $(type -p ggrep grep | head -1) -F "$query" || true
+  elmenv --definitions | $(type -p ggrep grep | head -1) -F "$query" || true
 }
 
 indent() {
@@ -93,7 +106,7 @@ for option in "${OPTIONS[@]}"; do
     HAS_PATCH="-p"
     ;;
   "version" )
-    exec ruby-build --version
+    exec elmenv --version
     ;;
   * )
     usage 1 >&2
@@ -160,7 +173,7 @@ if [ -d "${PREFIX}/bin" ]; then
   fi
 fi
 
-# If ELMENV_BUILD_ROOT is set, always pass keep options to ruby-build.
+# If ELMENV_BUILD_ROOT is set, always pass keep options to elmenv.
 if [ -n "${ELMENV_BUILD_ROOT}" ]; then
   export ELM_BUILD_BUILD_PATH="${ELMENV_BUILD_ROOT}/${VERSION_NAME}"
   KEEP="-k"
@@ -189,34 +202,11 @@ cleanup() {
 
 trap cleanup SIGINT
 
-# Invoke `ruby-build` and record the exit status in $STATUS.
+# Invoke `elmenv` and record the exit status in $STATUS.
 STATUS=0
-ruby-build $KEEP $VERBOSE $HAS_PATCH "$DEFINITION" "$PREFIX" || STATUS="$?"
-
-# Display a more helpful message if the definition wasn't found.
-if [ "$STATUS" == "2" ]; then
-  { candidates="$(definitions "$DEFINITION")"
-    here="$(dirname "${0%/*}")"
-    if [ -n "$candidates" ]; then
-      echo
-      echo "The following versions contain \`$DEFINITION' in the name:"
-      echo "$candidates" | indent
-    fi
-    echo
-    echo "See all available versions with \`elmenv install --list'."
-    echo
-    echo -n "If the version you need is missing, try upgrading ruby-build"
-    if [ "$here" != "${here#$(brew --prefix 2>/dev/null)}" ]; then
-      printf ":\n\n"
-      echo "  brew update && brew upgrade ruby-build"
-    elif [ -d "${here}/.git" ]; then
-      printf ":\n\n"
-      echo "  cd ${here} && git pull"
-    else
-      printf ".\n"
-    fi
-  } >&2
-fi
+echo "$VERSION"
+cd elm-platform/installers && runhaskell BuildFromSource.hs "$VERSION_NAME" || STATUS="$?"
+cd -
 
 # Execute `after_install` hooks.
 for hook in "${after_hooks[@]}"; do eval "$hook"; done
